import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import styles from './page.module.css'
import Context from '@/context/context'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Context>
          <main className={styles.main}>
            <Navbar />
            {children}
          </main>
        </Context>
      </body>
    </html>
  )
}
